### ISSUE TITLE
training error  "deriv sum is inf/nan"

### ISSUE THREAD

**Issue by Seventhen** [lingochamp/kaldi-ctc#1]
I modified the run script based on librispeech and all is ok in 30 hours corpus training. 

But in about 200 hours corpus training,  I encountered an error which called "sum == sum && "Error in this batch, deriv sum is inf/nan" in the source file named ctc-nnet-update source, which called warp-ctc function. I can't figure it out. 

Can anyone offer me some advices?

**Comment by lifeiteng** [comment]
What's the lengths of training sentences?
too long sentence will make training unstable.

**Comment by Seventhen** [comment]
First I used --max-allow-frames 2000, but it failed in about 140th iter. Then I changed to400, it could go further, but still failed

**Comment by lifeiteng** [comment]
try update warp-ctc, I noticed there are some bugs fixed.

**Comment by xinq2016** [comment]
Hi Lifeiteng,
With the latest warp-ctc, there is still the nan issue in about 34th iter for own mandarin corpus.
build_tree_mono=false
TreeLeaves=2500
minibatch_size=16
max-allow-frames=2000
subsampling-factor=1

**Comment by lifeiteng** [comment]
@xinq2016  try `subsampling-factor=3`
If the train sentences are too long, split them into smaller segments

**Comment by wblgers** [comment]
Hi,
I think this issue is not resolved. I use the following config:
minibatch_size=32
max-allow-frames=350
subsampling-factor=4

It will report this nan issue in about 51th iter. Ony when I decrease the max-allow-frames to ve 300, the training will pass. But during training there is so many warning "Too little feature frames.". And the increasing of accuracy is slow. 
Is there any solution for this nan issue? I mean from the code. Thanks!
